# Generated by Django 3.0.6 on 2020-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200509_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
