# Generated by Django 3.0.6 on 2020-05-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200509_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key_creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
