# Generated by Django 3.0.6 on 2020-05-09 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_activation_key_creation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activation_date',
            new_name='first_activation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activation_key_creation_time',
        ),
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('key', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('key_type', models.CharField(choices=[('pw', 'Password Forgotten'), ('a', 'activation')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
