# Generated by Django 3.0.6 on 2020-05-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20200509_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key_type',
            field=models.CharField(choices=[('pw', 'Password Forgotten'), ('a', 'Activation'), ('auth', 'Authentication')], max_length=4),
        ),
    ]
