# Generated by Django 3.0.6 on 2020-05-13 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('User', '0006_auto_20200509_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSession',
            fields=[
                ('key', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('token', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
