# Generated by Django 3.0.6 on 2020-05-13 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('User', '0007_opensession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('family', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('deactivating_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ip', models.GenericIPAddressField(editable=False)),
                ('browser', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='User.Browser')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('brand', 'family', 'model')},
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('family', 'version')},
            },
        ),
        migrations.DeleteModel(
            name='OpenSession',
        ),
        migrations.AddField(
            model_name='client',
            name='device',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='User.Device'),
        ),
        migrations.AddField(
            model_name='client',
            name='os',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='User.OS'),
        ),
        migrations.AddField(
            model_name='client',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
