# Generated by Django 3.0.6 on 2020-05-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20200513_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ua_string',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='browser',
            name='family',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='browser',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='family',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='os',
            name='family',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='os',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
